- name: Install Android SDK command-line tools
  run: |
    mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
    cd $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
    wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
    unzip -q *.zip
    mkdir -p latest
    mv cmdline-tools/* latest/
    yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
      "platform-tools" "build-tools;34.0.0" "platforms;android-34"
